### PR TITLE
Migrated from vows.js test-runner to mocha.js

### PR DESCRIPTION
**Pull request by camden**

### CODE REVIEW

**Comment by strugee** [comment]
Thanks, but I really prefer Vows. The plain-object philosophy is really neat and forces tests to be structured (and lets you do powerful things with reusability, etc.), and I very much like how it forces a separation between the topic and the assertions.

**Comment by camden** [comment]
@strugee As neat as the philosophy may be, Vows is breaking on some simple code. Check out the branch `failing-test` in [my fork](https://github.com/camden/node-git-clone-or-pull/blob/failing-test/test/lib/branch-test.js#L40-L44) (not sure why the indentation is so messed up). Try running `npm test`. The error (seen below) seems to be a Vows issue, since Vows uses `util.puts` and nothing else in the repo does.

screen shot 2017-04-04 at 5 04 13 pm

If we can solve this issue, I'd be able to move ahead (using Vows) with adding some intended functionality. If we can't, I think you should consider using Mocha. For a relatively small project such as this, it's really not so bad. :)

**Comment by strugee** [comment]
@camden ah yeah, that warning is completely unrelated to the "asynchronous error" you're seeing. I think this particular test suite is flaky, unfortunately. I can prioritize looking into it. (VowsJS recently changed maintainers too, so this will get better.)

Can you file an issue documenting what you intend to add, so I can comment on it?

**Comment by strugee** [comment]
@camden and in the future, unless a change is immediately obvious, a description would be nice. Something like you wrote in https://github.com/strugee/node-git-clone-or-pull/pull/8#issuecomment-291683034 would've been great in the PR description, since I originally saw this as something implementing something I didn't want to merge, and apparently solving no problems. The latter of which was clearly not the case :)

Thank you!

**Comment by camden** [comment]
@strugee Thanks for the quick response! I'll add an issue tomorrow morning (unless you'd rather I add a quick one right now -- typing from my phone so I don't want to do the whole thing now). Let me know if there's anything I can help with in terms of fixing Vows or finishing up the port to Mocha. 

The functionality I'm adding is a `depth` option. You can look at my changes in my fork if you'd like. 

Good call about adding a description. I'm still new at contributing to OSS. :)

Thanks!

**Comment by camden** [comment]
Ooh, huh, that's right. Looks like the console.log message is incidentally printing there. Still doesn't solve the issue but it's something. Am I using Vows incorrectly?

**Comment by strugee** [comment]
@camden ping? You were going to file an issue right?

I also still haven't looked into the problem you're having... this is all made more difficult by the fact that it Works On My Machine(tm).

**Comment by camden** [comment]
@strugee Sorry, it's been a busy week. I ended up just using my fork for the project I needed the `depth` functionality for. Since the issues only came up when trying to add the new functionality to your branch, and if it ain't broke, then at this point there's no need to file an issue.

**Comment by strugee** [comment]
@camden no problem.

Can you file an issue anyway? If you needed it it's quite possible someone else will too, and it'd be useful to have a todo in the issue tracker.

**Comment by strugee** [comment]
@camden by the way, I hope you aren't discouraged by this PR being closed. It's really cool that you want to contribute to freedom-respecting software/open source and I really hope you try again!

**Comment by camden** [comment]
@strugee Apologies, meant to respond to this and never did. 

To be frank, I'm not sure what the issue *is* -- all I know is that it doesn't seem to be related to your code/project at all (looks like a vows issue, or just me doing something wrong 😊). 

And I'm not discouraged!! Just busy 😄

**Comment by strugee** [comment]
@camden oh, when I said file an issue I didn't mean the Vows problem - I meant the feature you were originally planning to add :)

**Comment by camden** [comment]
Hey Alex,

I've added the issue [here.](https://github.com/strugee/node-git-clone-or-pull/issues/10)

Let me know how I can help out!

**Comment by strugee** [comment]
Hey @camden! Sorry for the late-ish response on this. Thanks for filing that issue!

I just switched the test framework to [Perjury][] which looks like Vows but is, you know, maintained. Hopefully that should alleviate some pain.

 [Perjury]: https://www.npmjs.com/package/perjury

**Comment by camden** [comment]
@strugee Sweet! I'll convert my tests over to Perjury when I find some time. :)

**Pull request closed without merging**
