### PR TITLE
Move jshint to devDeps

### PR DESCRIPTION
**Pull request by davej**
Shipping this as a production dep seems like a mistake. You may also want to update `package-lock.json`.

### CODE REVIEW

**Comment by strugee** [comment]
@davej thanks, nice catch! It was indeed a mistake. Can you update this PR to include the `package-lock.json` changes? I'd be happy to walk you through them. Alternately I can force-push to your branch, but it'd be easier to have you do them.

**Comment by davej** [comment]
Yeah just did the change on the github website rather than forking manually so I didn't update the package lock. I can do this when I'm in front of a computer next week.

**Comment by davej** [comment]
Ok. Updated PR.

**Comment by strugee** [comment]
No problem; I've been there :P

Small nit - could you capitalize "update" in "update package-lock.json"? Otherwise LGTM, thank you :thumbsup:

**Comment by strugee** [comment]
Or just squash them together, it doesn't matter terribly

**Comment by davej** [comment]
You can do a squash and merge from the Github PR by the way. Just click the arrow next to the merge button. 🙂

**Comment by strugee** [comment]
Lol, fair enough. I wrote https://github.com/strugee/node-git-clone-or-pull/pull/22#issuecomment-343809699 as an afterthought so I didn't think of it :P

**Comment by strugee** [comment]
3.1.1 is on npm :thumbsup:

**Pull request merged**
